// Code generated by protoc-gen-go. DO NOT EDIT.
// source: child.proto

/*
Package Transport is a generated protocol buffer package.

It is generated from these files:
	child.proto

It has these top-level messages:
	ChildUser
*/
package Transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChildUser struct {
	Fname string `protobuf:"bytes,1,opt,name=fname" json:"fname,omitempty"`
	Sname string `protobuf:"bytes,2,opt,name=sname" json:"sname,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *ChildUser) Reset()                    { *m = ChildUser{} }
func (m *ChildUser) String() string            { return proto.CompactTextString(m) }
func (*ChildUser) ProtoMessage()               {}
func (*ChildUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChildUser) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *ChildUser) GetSname() string {
	if m != nil {
		return m.Sname
	}
	return ""
}

func (m *ChildUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*ChildUser)(nil), "Transport.ChildUser")
}

func init() { proto.RegisterFile("child.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xc8, 0xcc,
	0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0c, 0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8,
	0x2f, 0x2a, 0x51, 0xf2, 0xe5, 0xe2, 0x74, 0x06, 0xc9, 0x84, 0x16, 0xa7, 0x16, 0x09, 0x89, 0x70,
	0xb1, 0xa6, 0xe5, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x20,
	0xd1, 0x62, 0xb0, 0x28, 0x13, 0x44, 0xb4, 0x18, 0x26, 0x9a, 0x9a, 0x9b, 0x98, 0x99, 0x23, 0xc1,
	0x0c, 0x11, 0x05, 0x73, 0x92, 0xd8, 0xc0, 0x16, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78,
	0xbf, 0x96, 0xb8, 0x6f, 0x00, 0x00, 0x00,
}
